import { jsPDF } from "jspdf"

const MM = 4.8

export type BarangayFacilityPermitInput = {
  reservationId: string
  permitRefNo: string
  facilityName: string
  applicantName: string
  applicantContact: string | null
  purpose: string
  reservationDate: string
  timeSlot: string
  issuedAtLabel: string
  orNo: string | null
}

function ensureSpace(doc: jsPDF, y: number, margin: number, need: number): number {
  const h = doc.internal.pageSize.getHeight()
  if (y + need > h - margin) {
    doc.addPage()
    return margin
  }
  return y
}

function labelValue(doc: jsPDF, margin: number, maxW: number, y: number, label: string, value: string): number {
  doc.setFont("helvetica", "bold")
  doc.setFontSize(9)
  doc.text(label, margin, y)
  y += MM * 0.8
  doc.setFont("helvetica", "normal")
  const lines = doc.splitTextToSize(value || "—", maxW)
  for (const line of lines) {
    y = ensureSpace(doc, y, margin, MM)
    doc.text(line, margin, y)
    y += MM * 0.85
  }
  return y + MM * 0.3
}

const TERMS = [
  "This permit authorizes use of the barangay facility only for the stated purpose and schedule.",
  "The applicant shall maintain cleanliness, follow barangay ordinances, and avoid noise or activities that disturb the neighborhood.",
  "The applicant is liable for any damage to property or equipment during the activity.",
  "This permit is non-transferable. Present a valid ID together with this document when requested by barangay personnel.",
]

/** Official barangay facility reservation permit (PDF blob for storage upload). */
export function generateBarangayFacilityPermitPdfBlob(input: BarangayFacilityPermitInput): Blob {
  const doc = new jsPDF({ unit: "mm", format: "a4" })
  const margin = 16
  const pageW = doc.internal.pageSize.getWidth()
  const maxW = pageW - margin * 2
  let y = margin

  doc.setFont("helvetica", "bold")
  doc.setFontSize(14)
  doc.text("BARANGAY FACILITY USE PERMIT", margin, y)
  y += 7
  doc.setFont("helvetica", "normal")
  doc.setFontSize(9)
  doc.setTextColor(70, 70, 70)
  doc.text("Digital permit — facility reservation", margin, y)
  y += 8
  doc.setTextColor(0, 0, 0)

  doc.setFont("helvetica", "bold")
  doc.setFontSize(10)
  doc.text(`Permit No: ${input.permitRefNo}`, margin, y)
  y += 5
  doc.setFont("helvetica", "normal")
  doc.setFontSize(9)
  doc.text(`Reservation ID: ${input.reservationId}`, margin, y)
  y += 4
  if (input.orNo) {
    doc.text(`Official Receipt: ${input.orNo}`, margin, y)
    y += 4
  }
  doc.text(`Issued: ${input.issuedAtLabel}`, margin, y)
  y += 10

  y = ensureSpace(doc, y, margin, 16)
  doc.setFont("helvetica", "bold")
  doc.setFontSize(10)
  doc.text("Applicant", margin, y)
  y += 5
  doc.setFont("helvetica", "normal")
  y = labelValue(doc, margin, maxW, y, "Name", input.applicantName)
  y = labelValue(doc, margin, maxW, y, "Contact", input.applicantContact?.trim() || "—")

  y += 4
  y = ensureSpace(doc, y, margin, 16)
  doc.setFont("helvetica", "bold")
  doc.setFontSize(10)
  doc.text("Facility and schedule", margin, y)
  y += 5
  doc.setFont("helvetica", "normal")
  y = labelValue(doc, margin, maxW, y, "Facility", input.facilityName)
  y = labelValue(doc, margin, maxW, y, "Purpose", input.purpose)
  y = labelValue(doc, margin, maxW, y, "Date", input.reservationDate)
  y = labelValue(doc, margin, maxW, y, "Time slot", input.timeSlot)

  y += 6
  y = ensureSpace(doc, y, margin, 24)
  doc.setFont("helvetica", "bold")
  doc.setFontSize(9)
  doc.text("Terms", margin, y)
  y += 5
  doc.setFont("helvetica", "normal")
  doc.setFontSize(8)
  TERMS.forEach((t, i) => {
    const block = `${i + 1}. ${t}`
    const wrapped = doc.splitTextToSize(block, maxW)
    for (const w of wrapped) {
      y = ensureSpace(doc, y, margin, MM * 0.7)
      doc.text(w, margin, y)
      y += MM * 0.75
    }
  })

  y += 8
  y = ensureSpace(doc, y, margin, 14)
  doc.setFontSize(8)
  doc.setTextColor(80, 80, 80)
  doc.text(
    "System-generated by Barangay Portal Management (BPM) after Punong Barangay approval and secretary issuance.",
    margin,
    y,
  )

  return doc.output("blob")
}
